import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const UIS = [
  { dist: "dist/src/ui/dashboard.html", out: "src/generated/dashboard-html.ts", name: "DASHBOARD_HTML" },
];

mkdirSync(join(root, "src/generated"), { recursive: true });

for (const { dist, out, name } of UIS) {
  const html = readFileSync(join(root, dist), "utf-8");
  writeFileSync(
    join(root, out),
    `// AUTO-GENERATED by scripts/bundle-html.ts - DO NOT EDIT\nexport const ${name} = ${JSON.stringify(html)};\n`
  );
  console.log(`Generated ${out} (${(html.length / 1024).toFixed(1)} KB)`);
}
